version: '3.9'

services:
  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - ./redis-data:/data
    ports:
      - 6379:6379
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./mongo-volume:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - 8081:8081
networks:
  default: 
    name: dev_network
